package halityurttas.com.tr.cloudminingprofitcalculator.entities;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CONTRACTS".
 */
@Entity
public class Contracts {

    @Id(autoincrement = true)
    private Long id;
    private int ghs;

    @NotNull
    private java.util.Date startDate;
    private Integer expire;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Contracts() {
    }

    public Contracts(Long id) {
        this.id = id;
    }

    @Generated
    public Contracts(Long id, int ghs, java.util.Date startDate, Integer expire) {
        this.id = id;
        this.ghs = ghs;
        this.startDate = startDate;
        this.expire = expire;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getGhs() {
        return ghs;
    }

    public void setGhs(int ghs) {
        this.ghs = ghs;
    }

    @NotNull
    public java.util.Date getStartDate() {
        return startDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartDate(@NotNull java.util.Date startDate) {
        this.startDate = startDate;
    }

    public Integer getExpire() {
        return expire;
    }

    public void setExpire(Integer expire) {
        this.expire = expire;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
