package halityurttas.com.tr.cloudminingprofitcalculator.entities;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import halityurttas.com.tr.cloudminingprofitcalculator.entities.Contracts;

import halityurttas.com.tr.cloudminingprofitcalculator.entities.ContractsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contractsDaoConfig;

    private final ContractsDao contractsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contractsDaoConfig = daoConfigMap.get(ContractsDao.class).clone();
        contractsDaoConfig.initIdentityScope(type);

        contractsDao = new ContractsDao(contractsDaoConfig, this);

        registerDao(Contracts.class, contractsDao);
    }
    
    public void clear() {
        contractsDaoConfig.clearIdentityScope();
    }

    public ContractsDao getContractsDao() {
        return contractsDao;
    }

}
